# Generated by Django 5.1.7 on 2025-04-24 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0004_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharma',
            name='category',
        ),
        migrations.AddField(
            model_name='pharma',
            name='categor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharma.categories'),
        ),
    ]
