# Generated by Django 5.1.7 on 2025-04-25 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0005_remove_pharma_category_pharma_categor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default=1, upload_to='pharma/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
            preserve_default=False,
        ),
    ]
