# Generated by Django 5.1.7 on 2025-04-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0007_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharma',
            name='Approval',
            field=models.BooleanField(default=False),
        ),
    ]
