# Generated by Django 5.1.7 on 2025-05-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0008_pharma_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharma',
            name='shipping',
            field=models.IntegerField(default=0),
        ),
    ]
