# Generated by Django 5.1.7 on 2025-05-01 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0009_pharma_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharma',
            name='categor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharma.categories', verbose_name='Category'),
        ),
    ]
