# Generated by Django 5.1.7 on 2025-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0013_payment_pending_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentmethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
            ],
        ),
    ]
