# Generated by Django 5.1.7 on 2025-05-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0014_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerinfo',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharma.paymentmethod'),
        ),
    ]
