# Generated by Django 5.1.7 on 2025-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0017_bought'),
    ]

    operations = [
        migrations.CreateModel(
            name='boughtitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('users', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('total_earned', models.IntegerField(default=0)),
                ('order_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
