# Generated by Django 5.1.7 on 2025-05-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0018_boughtitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtitem',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
