# Generated by Django 5.1.7 on 2025-05-06 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0019_alter_boughtitem_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtitem',
            name='buyer_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharma.buyerinfo'),
        ),
    ]
