# Generated by Django 5.1.7 on 2025-05-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0020_boughtitem_buyer_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popular',
            name='popular',
        ),
    ]
