# Generated by Django 5.1.7 on 2025-05-14 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0023_searchproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharma',
            name='image',
            field=models.ImageField(upload_to='pharma/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
