# Generated by Django 5.1.7 on 2025-05-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0024_alter_pharma_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='boughtitem',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
