# Generated by Django 5.1.7 on 2025-05-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0026_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bid',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bid',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
