# Generated by Django 5.1.7 on 2025-07-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0029_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved',
            name='user',
        ),
    ]
