# Generated by Django 5.1.7 on 2025-07-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0031_remove_approved_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharma',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
