# Generated by Django 5.1.7 on 2025-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0032_pharma_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharma',
            name='location',
            field=models.CharField(default='Ondo State', max_length=100),
        ),
    ]
