# Generated by Django 5.1.7 on 2025-08-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0033_pharma_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharma',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
