# Generated by Django 5.1.7 on 2025-08-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0034_alter_pharma_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
    ]
